### ISSUE TITLE
FOV in primaArray

### ISSUE THREAD

**Issue by TayebehY** [isetbio/EJLPhosphene#6]
Hi 

I am working on the electrical stimulation simulation (primaArray). However, the primaArray.compute only works when FOV is 1.7.
I would appreciate it if you let me know if I am making any mistakes or if this is supposed to work like this. 

Thank you so much

**Comment by jamesgolden1** [comment]
Hi Tayebeh, my apologies for the slow reply.

That restriction is in place because the reconstruction filters have only
been trained for this FOV.

I think you may be able to change the code to run the forward simulation
(resulting in RGC responses) for different FOV values, but you will not be
able to use the pretrained reconstruction filters (or at least you can only
use them for patches of FOV = 1.7 deg and stitch/tile them).

Another aspect of this is that the implementation of the RGC mosaic does
not account for the decreasing receptive field size of RGC responses with
increasing eccentricity. The simulation was meant to represent a small
patch of retina where this could be approximated by constant RF sizes (and
even this is not ideal). Larger FOV values would ideally also incorporate
changing RF size, but this would be difficult to implement.

James

**Comment by TayebehY** [comment]
Thank you so much for the response.
